<FORM>
자신의 자동차에 설치한 옵션은? <P>
<INPUT TYPE=CHECKBOX NAME=OP1 VALUE="YES">자동변속기
<INPUT TYPE=CHECKBOX NAME=OP2 VALUE="YES">에어콘
<INPUT TYPE=CHECKBOX NAME=OP3 VALUE="YES">에어백
<INPUT TYPE=CHECKBOX NAME=OP4 VALUE="YES">알루미늄휠
<INPUT TYPE=CHECKBOX NAME=OP5 VALUE="YES>자동백미러
<INPUT TYPE=CHECKBOX NAME=OP6 VALUE="YES">파워핸들
<P>
<INPUT TYPE="SUBMIT" VALUE="저장"> <INPUT TYPE="RESET" VALUE="지우기">
</FORM>
