<FORM>
자신이 졸업한 초등학교는? <P>
<SELECT NAME=SCHOOL>
<OPTION VALUE=01>은로 초등학교 </OPTION>
<OPTION VALUE=02>나라 초등학교 </OPTION>
<OPTION VALUE=03>한국 초등학교 </OPTION>
<OPTION VALUE=04>방배 초등학교 </OPTION>
<OPTION VALUE=05>중앙 초등학교 </OPTION>
<OPTION VALUE=06>배화 초등학교 </OPTION>
</SELECT>
<INPUT TYPE="SUBMIT" VALUE="저장"> <INPUT TYPE="RESET" VALUE="지우기">
</FORM>
