<FORM>
이름 : <INPUT TYPE=TEXT NAME=NAME SIZE=10><P>
나이 : <INPUT TYPE=TEXT NAME=AGE SIZE=3 MAXLENGTH=3><P>
주소 : <INPUT TYPE=TEXT NAME=JUSO SIZE=30><P>
비밀번호 : <INPUT TYPE=PASSWORD NAME=PASS SIZE=7><P>
<INPUT TYPE="SUBMIT" VALUE="저장"> <INPUT TYPE="RESET" VALUE="지우기">
</FORM>
