<FORM>
자신의 나이는? <P>
<INPUT TYPE=RADIO NAME=AGE VALUE="10">10대
<INPUT TYPE=RADIO NAME=AGE VALUE="20">20대
<INPUT TYPE=RADIO NAME=AGE VALUE="30" CHECKED>30대
<INPUT TYPE=RADIO NAME=AGE VALUE="40">40대
<INPUT TYPE=RADIO NAME=AGE VALUE="50">50대
<INPUT TYPE=RADIO NAME=AGE VALUE="60">60대
<P>
<INPUT TYPE="SUBMIT" VALUE="저장"> <INPUT TYPE="RESET" VALUE="지우기">
</FORM>
